## Author : 22200727
## Question 2
# The Fibonacci series 0, 1, 1, 2, 3, 5, 8, 13, . . . is generated by starting with 0, 1 and then each subsequent number is the sum of the two previous ones. Write a recursive function fib(n) that calculates the nth item of the Fibonacci series starting with 0, e.g. fib(6) should return 8. Don’t try to be efficient! Actually, how could you be more efficient?

def fib(n):
    # Base case: if n is 0 or 1, return n
    if n == 0:
        return 0
    elif n == 1:
        return 1
    # Recursive case: calculate Fibonacci number using recursion
    else:
        return fib(n - 1) + fib(n - 2)

# Example usage:
result = fib(6)
print(result)  # Output: 8 (since fib(6) = 0, 1, 1, 2, 3, 5, 8)
